config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  get 'story' => 'pages#story'
  get 'accommodations' => 'pages#accommodations'
  get 'photos' => 'pages#photos'
  get 'gifts' => 'pages#gifts'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def story
  end

	def accommodations
  end

  def photos
  end

  def gifts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="center" style="color: #BDBDBD; margin-bottom: 10px; margin-top: 40px;">
	#BritaPhilter
	<br /><br />
	<small><%= link_to "Made", "creation.txt", :style => "color: #BDBDBD; text-decoration: underline;" %> by Phil</small>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--%= link_to (image_tag "logo.png", :size => "267x25", :title => "Brittany + Phil"), root_path, class: "navbar-brand" %-->
      <%= link_to (image_tag "fliplogo.gif", :size => "20x20", :title => "Brittany + Phil"), root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "WEDDING", root_path %></li> 
        <li class="<%= 'active' if current_page?(story_path) %>"><%= link_to "OUR STORY", story_path %></li> 
        <li class="<%= 'active' if current_page?(accommodations_path) %>"><%= link_to "ACCOMMODATIONS", accommodations_path %></li> 
        <li class="<%= 'active' if current_page?(photos_path) %>"><%= link_to "PHOTOS", photos_path %></li> 
        <li class="<%= 'active' if current_page?(gifts_path) %>"><%= link_to "GIFTS", gifts_path %></li> 
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

<script>
$(".nav a").on("click", function(){
   $(".nav").find(".active").removeClass("active");
   $(this).parent().addClass("active");
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Brittany + Phil's Wedding</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= tag :meta, name: "viewport", content: "width=device-width, initial-scale=1.0" %>


  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="//blueimp.github.io/Gallery/css/blueimp-gallery.min.css">
	<link rel="stylesheet" href="assets/stylesheets/bootstrap-image-gallery.min.css">
</head>
<body>
	<%= yield %>
</body>
</html>

app/views/pages/accommodations.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--%= link_to (image_tag "logo.png", :size => "267x25", :title => "Brittany + Phil"), root_path, class: "navbar-brand" %-->
      <%= link_to (image_tag "fliplogo.gif", :size => "20x20", :title => "Brittany + Phil"), root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "WEDDING", root_path %></li> 
        <li class="<%= 'active' if current_page?(story_path) %>"><%= link_to "OUR STORY", story_path %></li> 
        <li class="<%= 'active' if current_page?(accommodations_path) %>"><%= link_to "ACCOMMODATIONS", accommodations_path %></li> 
        <li class="<%= 'active' if current_page?(photos_path) %>"><%= link_to "PHOTOS", photos_path %></li> 
        <li class="<%= 'active' if current_page?(gifts_path) %>"><%= link_to "GIFTS", gifts_path %></li> 
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

<script>
$(".nav a").on("click", function(){
   $(".nav").find(".active").removeClass("active");
   $(this).parent().addClass("active");
});
</script>

<div class="container" style ="padding-top: 50px;">
  <div class="center" style="margin-top: 30px;">
  	<%= image_tag "accommodations.png", :class => "img-responsive", :style => "margin: 0 auto;", :title => "Accommodations" %>
  	<hr width="25%">
  	<br />
  	<div class="row">
  		<div class="col-md-6 col-md-offset-3" style="line-height: 2.0;">
  			We have booked a block of rooms at the Hilton Orrington, which is about a block away from the wedding venue. To book, please <%= link_to "visit this site", "http://www.hilton.com/en/hi/groups/personalized/O/ORDOEHF-DNW-20160712/index.jhtml?WT.mc_id=POG", :style => "color: #333333; text-decoration: underline;" %>.
  		</div>
  	</div>
  	<br />
  	<%= image_tag "hiltonorrington.png", :class => "img-responsive", :style => "margin: 0 auto;", :title => "Hilton Orrington" %>
  	<br />
  	<div class="party_name">HILTON ORRINGTON</div>
  	<div class="party_description">
  		1710 Orrington Avenue<br />
  		Evanston, IL 60201<br />
  		847-866-8700<br />
  		<%= link_to "www.hotelorrington.com", "http://www.hilton.com/en/hi/groups/personalized/O/ORDOEHF-DNW-20160712/index.jhtml?WT.mc_id=POG", :style => "color: #333333; text-decoration: underline;" %>
  	</div>

  </div>
</div>

<div class="center" style="color: #BDBDBD; margin-bottom: 10px; margin-top: 40px;">
	#BritaPhilter
	<br /><br />
	<small><%= link_to "Made", "creation.txt", :style => "color: #BDBDBD; text-decoration: underline;" %> by Phil</small>
</div>

app/views/pages/gifts.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--%= link_to (image_tag "logo.png", :size => "267x25", :title => "Brittany + Phil"), root_path, class: "navbar-brand" %-->
      <%= link_to (image_tag "fliplogo.gif", :size => "20x20", :title => "Brittany + Phil"), root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "WEDDING", root_path %></li> 
        <li class="<%= 'active' if current_page?(story_path) %>"><%= link_to "OUR STORY", story_path %></li> 
        <li class="<%= 'active' if current_page?(accommodations_path) %>"><%= link_to "ACCOMMODATIONS", accommodations_path %></li> 
        <li class="<%= 'active' if current_page?(photos_path) %>"><%= link_to "PHOTOS", photos_path %></li> 
        <li class="<%= 'active' if current_page?(gifts_path) %>"><%= link_to "GIFTS", gifts_path %></li> 
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

<script>
$(".nav a").on("click", function(){
   $(".nav").find(".active").removeClass("active");
   $(this).parent().addClass("active");
});
</script>

<div class="container" style ="padding-top: 50px;">
  <div class="center" style="margin-top: 30px;">
  	<%= image_tag "gifts.png", :class => "img-responsive", :style => "margin: 0 auto;", :title => "Registry" %>
  	<hr width="25%">
  	<br />
  	<div class="row">
  		<div class="col-md-3 col-md-offset-3">
  			<%= link_to (image_tag "bedbathbeyond.png", :class => "img-responsive", :style => "margin: 0 auto;", :title => "Bed Bath & Beyond"), "http://www.bedbathandbeyond.com/store/giftregistry/view_registry_guest.jsp?pwsToken=&eventType=Wedding&registryId=543212605" %>
  		</div>
  		<div class="col-md-3">
  			<%= link_to (image_tag "bloomingdales.png", :class => "img-responsive", :style => "margin: 0 auto;", :title => "Bloomingdales"), "http://www.bloomingdales.com/registry/wedding/guest/?registryId=6568256" %>
  		</div>
  	</div>
  </div>
</div>

<div class="center" style="color: #BDBDBD; margin-bottom: 10px; margin-top: 40px;">
	#BritaPhilter
	<br /><br />
	<small><%= link_to "Made", "creation.txt", :style => "color: #BDBDBD; text-decoration: underline;" %> by Phil</small>
</div>

app/views/pages/home.html.erb
<div class="jumbotron">
	<div class="container center">
		<%= image_tag "buffalo_icon_pete.png", class: "img-responsive", :style => "margin: 0 auto; max-width: 50%;" %>
		<br><br><br><br>
		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<h1 class="cabin display-2" style="color: #221427; line-height: 1.2"><font style="color: #a7d1e9; background-color: #fa6c6a;">Buffalo</font> <font style="color: #f8ea9c; background-color: #fa6c6a;">Buffalo</font> is a unique experience for those able to seek the answer by the end of today.</h1>
			</div>
		</div>
	</div>
</div>
<div class="jumbotron" style="background-color: #fa6c6a;">
	<div class="container center">
		<div class="row">
			<div class="col-md-10 offset-md-1">
				<h1 class="cabin display-4" style="color: #221427; line-height: 1.2">"We first hear of the bison from Cortez and his followers in 1521. <font style="color: #a7d1e9;">Mo</font>n<font style="color: #a7d1e9;">t</font>e<font style="color: #a7d1e9;">zu</font>m<font style="color: #a7d1e9;">a</font> had one in a zoological garden, the specimen, in all probability, having been caught in Coahuila. As to their numbers, they were like the sands of the seashore, and the <font style="color: #a7d1e9;">account</font>s given by those who hunted them 20 or 30 years ago, today seem like vagaries of a disordered imagination.
				<br><br>Mr. Hornaday, who has hunted in South and Central Africa, where game is remarkably plentiful, states that the bison of this country previous to 1870 <font style="color: #a7d1e9;">exce</font>eded, in all probability, all the African game of every kind. An Army officer in service on the plains in 1867 stated to the writer that on one occasion he was surrounded by buffaloes, and that from the top of a small hill he could see nothing but a black mass of their bodies. It was impossible to estimate their numbers, and the party were in great fear lest they should be caught in a stampede, the rush being irresistible."</h1>
			</div>
		</div>
	</div>
</div>

app/views/pages/photos.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--%= link_to (image_tag "logo.png", :size => "267x25", :title => "Brittany + Phil"), root_path, class: "navbar-brand" %-->
      <%= link_to (image_tag "fliplogo.gif", :size => "20x20", :title => "Brittany + Phil"), root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "WEDDING", root_path %></li> 
        <li class="<%= 'active' if current_page?(story_path) %>"><%= link_to "OUR STORY", story_path %></li> 
        <li class="<%= 'active' if current_page?(accommodations_path) %>"><%= link_to "ACCOMMODATIONS", accommodations_path %></li> 
        <li class="<%= 'active' if current_page?(photos_path) %>"><%= link_to "PHOTOS", photos_path %></li> 
        <li class="<%= 'active' if current_page?(gifts_path) %>"><%= link_to "GIFTS", gifts_path %></li> 
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

<script>
$(".nav a").on("click", function(){
   $(".nav").find(".active").removeClass("active");
   $(this).parent().addClass("active");
});
</script>

<div class="container" style ="padding-top: 50px;">
    <div class="center" style="margin-top: 30px;">
    	<%= image_tag "photos.png", :class => "img-responsive", :style => "margin: 0 auto;", :title => "Photos" %>
    	<hr width="25%">
    	<br />
    	<div>

    		<div id="links">
        <a href="assets/2015maine.jpg" title="Maine 2015 - Weekend after we got engaged" data-gallery>
            <img src="assets/2015maine-thumb.jpg" alt="Maine 2015">
        </a>
        <a href="assets/2015berlin.jpg" title="Germany 2015 - Checking out the Berlin Wall" data-gallery>
            <img src="assets/2015berlin-thumb.jpg" alt="Berlin 2015">
        </a>
        <a href="assets/2015japan.jpg" title="Japan 2015 - At Kinkaku-ji, the golden pavilion" data-gallery>
            <img src="assets/2015japan-thumb.jpg" alt="Japan 2015">
        </a>
        <a href="assets/2014macau.jpg" title="Macau 2014 - At the Ruins of St. Paul" data-gallery>
            <img src="assets/2014macau-thumb.jpg" alt="Macau 2014">
        </a>
        <a href="assets/2014hongkong.jpg" title="Hong Kong 2014 - Victoria Peak overlooking the city" data-gallery>
            <img src="assets/2014hongkong-thumb.jpg" alt="Hong Kong 2014">
        </a>
        <a href="assets/2014cambodia.jpg" title="Cambodia 2014 - At Angkor Wat" data-gallery>
            <img src="assets/2014cambodia-thumb.jpg" alt="Cambodia 2014">
        </a>
        <a href="assets/2014thailand.jpg" title="Thailand 2014 - Checking out the temples in Bangkok" data-gallery>
            <img src="assets/2014thailand-thumb.jpg" alt="Thailand 2014">
        </a>
        <a href="assets/2014napa.jpg" title="Napa 2014 - Wine tasting at Frog's Leap" data-gallery>
            <img src="assets/2014napa-thumb.jpg" alt="Napa 2014">
        </a>
        <a href="assets/2013maine.jpg" title="Maine 2013 - There used to be a lobster on the table" data-gallery>
            <img src="assets/2013maine-thumb.jpg" alt="Maine 2013">
        </a>
        <a href="assets/2013vienna.jpg" title="Austria 2013 - At Brittany's favorite gelato place in Vienna" data-gallery>
            <img src="assets/2013vienna-thumb.jpg" alt="Vienna 2013">
        </a>
        <a href="assets/2013paris.jpg" title="France 2013 - Rainy day in champagne country" data-gallery>
            <img src="assets/2013paris-thumb.jpg" alt="Paris 2013">
        </a>
        <a href="assets/2013uk.jpg" title="UK 2013 - Sunday roast with Serene" data-gallery>
            <img src="assets/2013uk-thumb.jpg" alt="UK 2013">
        </a>
        <a href="assets/2012napa.jpg" title="Napa 2012 - Champagne tasting at Domaine Chandon" data-gallery>
            <img src="assets/2012napa-thumb.jpg" alt="Napa 2012">
        </a>
        <a href="assets/2012santabarbara.jpg" title="Santa Barbara 2012 - At the Old Mission" data-gallery>
            <img src="assets/2012santabarbara-thumb.jpg" alt="Santa Barbara 2012">
        </a>
        <a href="assets/2009vegas.jpg" title="Las Vegas 2009 - The weekend of our first date" data-gallery>
            <img src="assets/2009vegas-thumb.jpg" alt="Las Vegas 2009">
        </a>
    		</div>


    	</div>
    </div>

    <!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
    <div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
        <!-- The container for the modal slides -->
        <div class="slides"></div>
        <!-- Controls for the borderless lightbox -->
        <h3 class="title"></h3>
        <a class="prev">‹</a>
        <a class="next">›</a>
        <a class="close">×</a>
        <a class="play-pause"></a>
        <ol class="indicator"></ol>
        <!-- The modal dialog, which will be used to wrap the lightbox content -->
        <div class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" aria-hidden="true">&times;</button>
                        <h4 class="modal-title"></h4>
                    </div>
                    <div class="modal-body next"></div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default pull-left prev">
                            <i class="glyphicon glyphicon-chevron-left"></i>
                            Previous
                        </button>
                        <button type="button" class="btn btn-primary next">
                            Next
                            <i class="glyphicon glyphicon-chevron-right"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="//blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>
    <script src="assets/javascripts/bootstrap-image-gallery.min.js"></script>
</div>

<div class="center" style="color: #BDBDBD; margin-bottom: 10px; margin-top: 40px;">
    #BritaPhilter
    <br /><br />
    <small><%= link_to "Made", "creation.txt", :style => "color: #BDBDBD; text-decoration: underline;" %> by Phil</small>
</div>

app/views/pages/story.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--%= link_to (image_tag "logo.png", :size => "267x25", :title => "Brittany + Phil"), root_path, class: "navbar-brand" %-->
      <%= link_to (image_tag "fliplogo.gif", :size => "20x20", :title => "Brittany + Phil"), root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "WEDDING", root_path %></li> 
        <li class="<%= 'active' if current_page?(story_path) %>"><%= link_to "OUR STORY", story_path %></li> 
        <li class="<%= 'active' if current_page?(accommodations_path) %>"><%= link_to "ACCOMMODATIONS", accommodations_path %></li> 
        <li class="<%= 'active' if current_page?(photos_path) %>"><%= link_to "PHOTOS", photos_path %></li> 
        <li class="<%= 'active' if current_page?(gifts_path) %>"><%= link_to "GIFTS", gifts_path %></li> 
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

<script>
$(".nav a").on("click", function(){
   $(".nav").find(".active").removeClass("active");
   $(this).parent().addClass("active");
});
</script>

<div class="container" style ="padding-top: 50px;">
	<div class="center" style="margin-top: 30px;">
		<%= image_tag "ourstory.png", :class => "img-responsive", :style => "margin: 0 auto;", :title => "Our Story" %>
		<hr width="25%">
		<br />
		<div class="row">
			<div class="col-md-4" style="margin-bottom: 60px;">
				<%= image_tag "brittany.png", :class => "img-responsive", :style => "margin: 0 auto;", :title => "Brittany D'Arcy" %>
				<h2 class="party_name">HER STORY</h2>
				<br />
				<p class="party_description">
					Brittany D'Arcy was born in Champaign, IL and grew up in Highland Park, IL. She attended the University of Illinois at Urbana-Champaign where she studied Finance and Accountancy. After graduation, she joined an investment bank for two years before transitioning to private equity and impact investing.
				</p>
			</div>
			<div class="col-md-4" style="margin-bottom: 60px;">
				<%= image_tag "phil-spacer.png", :class => "img-responsive visible-md visible-lg", :style => "margin: 0 auto;", :title => "Phil Nguyen" %>
				<%= image_tag "phil.png", :class => "img-responsive visible-xs visible-sm", :style => "margin: 0 auto;", :title => "Phil Nguyen" %>
				<h2 class="party_name">HIS STORY</h2>
				<br />
				<p class="party_description">
					Phil Nguyen was born in Evanston, IL and grew up in Buffalo Grove, IL. He attended the University of Illinois at Urbana-Champaign where he studied Finance and Accountancy. After graduation, he spent four years working in finance before joining a startup based in New York City. He also writes a daily newsletter called <%= link_to "The Daily Water Cooler", "http://www.dailywatercooler.com/", :style => "color: #333333; text-decoration: underline;"  %>.
				</p>
			</div>
			<div class="col-md-4" style="margin-bottom: 60px;">
				<%= image_tag "couch-spacer.png", :class => "img-responsive visible-md visible-lg", :style => "margin: 0 auto;", :title => "Cat Couch" %>
				<%= image_tag "couch.png", :class => "img-responsive visible-xs visible-sm", :style => "margin: 0 auto;", :title => "Cat Couch" %>
				<h2 class="party_name">OUR STORY</h2>
				<br />
				<p class="party_description">
					We met during our junior year of college. We shared many finance and accounting courses and loved to study together. We were engaged in August 2015 and now we're about to get married!
				</p>
			</div>
		
	</div>
</div>

<div class="center" style="color: #BDBDBD; margin-bottom: 10px; margin-top: 40px;">
	#BritaPhilter
	<br /><br />
	<small><%= link_to "Made", "creation.txt", :style => "color: #BDBDBD; text-decoration: underline;" %> by Phil</small>
</div>